version: '3'

services:
  web:  
    build: .
    command: gunicorn --workers=1 -k gevent final_proj_blog.wsgi:application --bind 0.0.0.0:8000
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER="mysuperuser"
      - POSTGRES_PASSWORD="mysuperuser"
      - POSTGRES_DB="backendcourse"

volumes:
  postgres_data: