# version: '3'

services:
  web:  
    build: .
    command: gunicorn --workers=1 final_proj_blog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=yooobwoood
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=final_proj_blog_dev
volumes:
  postgres_data:
